### PR TITLE
added libxext6:i386 dependency for .deb

### PR DESCRIPTION
**Pull request by plata**
see #1010

### CODE REVIEW

**Comment by TriMoon** [comment]
Does this mean POL5 will be 32bits only?
I was hoping on a version for 64bit...

**Comment by plata** [comment]
The dependency is a runtime dependency which is needed by Wine. It doesn't say anything about Phoenicis PlayOnLinux/PlayOnMac (which is written in Java, so 32/64bit really doesn't matter that much).

**Comment by TriMoon** [comment]
@plata there also is a wine 64bit IIRC.
Besides It matters for those on 64bit linux, because the package won't even show-up in the package listing.
fe. i just checked while using 64bit Debian 9 (testing), and it isn't listed, and i'm not going to install 32bit architecture aside on a 64bit only system...

**Comment by plata** [comment]
The thing is that the used Wine architecture (x86/amd64) depends on the installation script and not on the Phoenicis software. As many scripts are using 32bit Wine, adding this dependency to the .deb is an easy way to ensure that the average user can use the scripts without installing the dependency manually. I agree that it's not optimal, so if you have any better ideas, let me know.

**Pull request merged**
