### PR TITLE
.deb: added openjfx dependency

### LINKED ISSUE #741: Check .deb dependencies
E.g. JavaFX is missing.

The dependencies are specified in `phoenicis-dist/src/deb/control/control`.

### PR DESCRIPTION
**Pull request by plata**
fixes #741

### CODE REVIEW

**Comment by BloodyIron** [comment]
I can't find them, where can we get deb versions of POL5?

**Comment by madoar** [comment]
@BloodyIron the repository doesn't contain the `.deb` installer, but it provides you with a script, which builds a `.deb` installer, which you can use to install POL 5 on your system.
To build this `.deb` installer you need to first clone the repository.
In addition you need to install java 8 and maven 3.
Next you need to execute the following command inside the cloned folder: `mvn clean package` 
After the command finished, you can find the file `phoenicis-dist_5.0~SNAPSHOT_all.deb` inside the `phoenicis-dist/target` directory.

**Comment by BloodyIron** [comment]
Is there any way we could get POL5 built already for us in deb form? I mean, wasn't that kind of pipeline already being done for POL4? Getting each user to compile their own deb is horribly inefficient.

**Comment by plata** [comment]
@BloodyIron we will provide the .deb in the future. Currently, we are in an early development phase (pre-alpha). This is the reason why we do not provide a .deb (yet).

**Comment by BloodyIron** [comment]
Oops! I thought it was further along. Any chance we could maybe get a news post on the POL site? I know that's off topic, but it might help clear up misunderstandings like this. :)

**Comment by plata** [comment]
I totally understand your point. We can ask @qparis if he would like to do this or if we wait until alpha (or if we go to alpha already).

**Comment by BloodyIron** [comment]
Yeah no worries, it's going to be you guys figuring out what you're most comfortable talking about. But some people think the POL project is dead, and a lack of mod activity on the forums doesn't help that either. Clearly development _IS_ happening, despite that perception.

**Comment by plata** [comment]
I know. I would have the same impression if I didn't know the GitHub repository.

@qparis probably it would really be a good idea to write a news which at least clarifies that Phoenicis is being developed, a new website is coming etc.

**Pull request merged**
