### PR TITLE
run formatter

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by plata** [comment]
Why did Travis fail? I didn't change anything.

**Comment by madoar** [comment]
The error message says, the test failed because it timed out. Can you restart the tests?
I don't think I have the necessary permissions.

**Comment by plata** [comment]
I saw that there was a timeout but why? Can we change anything to avoid this in the future?

**Comment by madoar** [comment]
I'm not sure how the timeout was produced, but I believe the cause was junit.
The question is do we have test methods that are marked with a timeout, or a rule? (see also [here](https://github.com/junit-team/junit4/wiki/timeout-for-tests))

**Comment by plata** [comment]
Should be AppConfigurationInitialisationTest.java.

**Pull request merged**
