### PR TITLE
updated after moving repository to PhoenicisOrg

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by plata** [comment]
Now the question: Do I merge or wait until Jenkins runs again?

**Comment by madoar** [comment]
Your choice :P

**Comment by plata** [comment]
I'll wait. Then @qparis can check what's the matter with Jenkins.

**Comment by qparis** [comment]
ok to test

**Comment by plata** [comment]
Seems like the master branch is not protected anymore. At least, the Jenkins results are not indicated by a green check mark.

**Comment by madoar** [comment]
@plata if this is finished from your side I think we can merge this.

**Comment by plata** [comment]
Ok, I will merge. Nevertheless I think @qparis should have a look at the settings again to make the Jenkins run required.

**Pull request merged**
